#!/usr/bin/env node
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

function parseArgs(argv) {
  const options = {
    output: '',
    rootSelector: '.mod-settings, .vertical-tab-content, .modal-content',
    targetSelector: '[data-settings-target="{target}"]',
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    switch (arg) {
      case '--output':
        options.output = argv[++index] ?? '';
        break;
      case '--root-selector':
        options.rootSelector = argv[++index] ?? '';
        break;
      case '--target-selector':
        options.targetSelector = argv[++index] ?? '';
        break;
      case '--help':
        printHelp();
        process.exit(0);
        break;
      default:
        throw new Error(`Unknown argument: ${arg}`);
    }
  }

  if (!options.output) {
    throw new Error('--output is required');
  }
  return options;
}

function printHelp() {
  console.log(`Usage: node scripts/obsidian_debug_settings_deeplink_template.mjs --output .obsidian-debug/settings-deeplink-assertion.js [options]

Generates a generic obsidian_eval_file.mjs assertion template for settings-page deep links.
Edit the generated ACTIONS array to open the source UI and trigger each deep-link button.

Options:
  --output <path>            Assertion JS file to write.
  --root-selector <selector> Settings scroll/root selector to inspect.
  --target-selector <sel>    Target selector template. Use {target}; defaults to [data-settings-target="{target}"].
  --help                     Show this help.
`);
}

function jsString(value) {
  return JSON.stringify(value);
}

function buildTemplate(options) {
  return `// Generated by obsidian_debug_settings_deeplink_template.mjs.
// Run with:
// node scripts/obsidian_eval_file.mjs --vault-name "<vault>" --file "${path.basename(options.output)}" --clear-before --capture-after --output .obsidian-debug/settings-deeplink-result.json

const ROOT_SELECTOR = ${jsString(options.rootSelector)};
const TARGET_SELECTOR = ${jsString(options.targetSelector)};

// Replace each action with plugin-specific UI interaction.
// action() should click the source control that opens settings and navigates to the target.
const ACTIONS = [
  {
    id: 'example',
    expectedTarget: 'example-target',
    expectedActivePrimary: null,
    expectedActiveSecondary: null,
    action() {
      throw new Error('Replace ACTIONS with plugin-specific deep-link interactions');
    },
  },
];

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function findScrollContainer(root) {
  const candidates = [
    root.closest('.vertical-tab-content'),
    root.closest('.vertical-tab-content-container'),
    root.closest('.modal-content'),
    root,
  ].filter(Boolean);
  return candidates.find((element) => element.scrollHeight > element.clientHeight) || candidates[0] || document.scrollingElement;
}

function activeTabText(selector) {
  const element = document.querySelector(selector);
  return element?.textContent?.trim() || element?.getAttribute('data-tab-id') || null;
}

function focusTargetLeaf(expectedTarget) {
  const escapedTarget = CSS.escape(expectedTarget);
  const target = document.querySelector(\`[data-settings-target="\${escapedTarget}"]\`);
  if (!target) return { ok: false, reason: 'target-not-found' };
  const leaf = target.closest('.workspace-leaf');
  if (!leaf) return { ok: false, reason: 'no-leaf' };
  if (!leaf.classList.contains('mod-active')) {
    const parent = leaf.parentElement;
    if (parent) {
      for (const sibling of parent.children) {
        if (sibling !== leaf && sibling.classList.contains('workspace-leaf')) {
          sibling.classList.remove('mod-active');
        }
      }
    }
    leaf.classList.add('mod-active');
  }
  return { ok: true };
}

function measureTarget(expectedTarget) {
  const root = document.querySelector(ROOT_SELECTOR) || document.body;
  const escapedTarget = CSS.escape(expectedTarget);
  const targetSelector = TARGET_SELECTOR.includes('{target}')
    ? TARGET_SELECTOR.replaceAll('{target}', escapedTarget)
    : \`\${TARGET_SELECTOR}[data-settings-target="\${escapedTarget}"]\`;
  const target = document.querySelector(targetSelector)
    || document.querySelector(\`[data-settings-target="\${escapedTarget}"]\`);
  if (!target) {
    return { ok: false, reason: 'target-not-found', expectedTarget };
  }

  const scrollContainer = findScrollContainer(root);
  const targetRect = target.getBoundingClientRect();
  const containerRect = scrollContainer.getBoundingClientRect();
  const targetTopDelta = targetRect.top - containerRect.top;
  return {
    ok: targetTopDelta >= -8 && targetTopDelta <= Math.max(160, containerRect.height / 3),
    expectedTarget,
    targetText: target.textContent?.trim()?.slice(0, 160) || '',
    scrollContainerClass: scrollContainer.className || scrollContainer.tagName,
    scrollTop: scrollContainer.scrollTop,
    targetTopDelta,
  };
}

const results = [];
for (const item of ACTIONS) {
  await item.action();
  await sleep(700);
  focusTargetLeaf(item.expectedTarget);
  await sleep(200);
  const measurement = measureTarget(item.expectedTarget);
  const activePrimary = activeTabText('.opencodian-settings-tab-primary.opencodian-settings-tab-active');
  const activeSecondary = activeTabText('.opencodian-settings-tab-secondary.opencodian-settings-tab-active');
  results.push({
    id: item.id,
    ok: measurement.ok
      && (!item.expectedActivePrimary || activePrimary === item.expectedActivePrimary)
      && (!item.expectedActiveSecondary || activeSecondary === item.expectedActiveSecondary),
    measurement,
    activePrimary,
    activeSecondary,
    expectedActivePrimary: item.expectedActivePrimary,
    expectedActiveSecondary: item.expectedActiveSecondary,
  });
}

return {
  ok: results.every((result) => result.ok),
  results,
};
`;
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  await mkdir(path.dirname(options.output), { recursive: true });
  await writeFile(options.output, buildTemplate(options), 'utf8');
  console.log(`Wrote settings deep-link assertion template: ${options.output}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
