#!/usr/bin/env python3
"""Validate Markdown generated by the math-to-obsidian-note skill."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


DEFAULT_VAULT_ROOT = Path(r"C:\Users\lt\Desktop\Obsidian Vault\数学")
DEFAULT_PROBLEM_DIR = DEFAULT_VAULT_ROOT / "高中数学" / "答疑"
FILENAME_RE = re.compile(r"^.+-.+-\d{4}-\d{4}-\d{4}\.md$", re.UNICODE)
FORBIDDEN_HEADING_RE = re.compile(
    r"^#{1,6}\s*(原始内容整理|来源图片|图表处理|处理说明|相关链接)\b",
    re.MULTILINE,
)
SOURCE_PATH_RE = re.compile(
    r"([A-Za-z]:\\Users\\|[A-Za-z]:\\.*\\(Pictures|Camera Roll|问题)\\|/Users/|/Volumes/)"
)
QUESTION_CALLOUT_RE = re.compile(r"^>\s*\[!question\]", re.MULTILINE)
WIKILINK_RE = re.compile(r"!?\[\[[^\]]+\]\]")
BAD_FRONTMATTER_KEYS = {
    "image_redraw",
    "ocr",
    "ocr_status",
    "tool_status",
    "gpt_image",
    "gpt_image_2",
    "created",
    "modified",
    "generated_by",
}


def split_frontmatter(text: str) -> tuple[str, str]:
    if not text.startswith("---\n") and not text.startswith("---\r\n"):
        return "", text
    normalized = text.replace("\r\n", "\n")
    end = normalized.find("\n---\n", 4)
    if end == -1:
        return "", text
    return normalized[4:end], normalized[end + 5 :]


def is_relative_to(path: Path, root: Path) -> bool:
    try:
        path.resolve().relative_to(root.resolve())
        return True
    except ValueError:
        return False


def parse_braced_arg(text: str, start: int) -> tuple[int, int] | None:
    i = start
    while i < len(text) and text[i].isspace():
        i += 1
    if i >= len(text) or text[i] != "{":
        return None
    depth = 0
    for j in range(i, len(text)):
        ch = text[j]
        if ch == "{" and (j == 0 or text[j - 1] != "\\"):
            depth += 1
        elif ch == "}" and (j == 0 or text[j - 1] != "\\"):
            depth -= 1
            if depth == 0:
                return i + 1, j
    return None


def dfrac_argument_ranges(text: str) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    for match in re.finditer(r"\\dfrac\b", text):
        first = parse_braced_arg(text, match.end())
        if not first:
            continue
        second = parse_braced_arg(text, first[1] + 1)
        if not second:
            continue
        ranges.extend([first, second])
    return ranges


def validate_frac_usage(text: str) -> list[str]:
    errors: list[str] = []
    ranges = dfrac_argument_ranges(text)
    for match in re.finditer(r"\\frac\b", text):
        pos = match.start()
        nested = any(start <= pos < end for start, end in ranges)
        if not nested:
            line = text.count("\n", 0, pos) + 1
            errors.append(
                f"Line {line}: use \\dfrac instead of \\frac for non-nested fractions."
            )
    return errors


def validate(
    path: Path,
    vault_root: Path,
    allow_wikilinks: bool,
    content_type: str,
    topic_dir: str | None,
    explicit_destination: bool,
) -> list[str]:
    errors: list[str] = []

    if path.suffix.lower() != ".md":
        errors.append("File must be a .md Markdown file.")
    if not FILENAME_RE.match(path.name):
        errors.append("Filename must match 大方向-细分方向-年-月日-小时分钟.md.")
    if path.exists() and not is_relative_to(path, vault_root):
        errors.append(f"File must be under {vault_root}.")

    resolved = path.resolve()
    problem_dir = (vault_root / "高中数学" / "答疑").resolve()
    if not explicit_destination and content_type == "problem" and resolved.parent != problem_dir:
        errors.append(f"Problem notes must be saved under {problem_dir}.")
    if not explicit_destination and content_type == "knowledge":
        if not topic_dir:
            errors.append("Knowledge notes require --topic-dir <大方向>.")
        else:
            expected = (vault_root / "高中数学" / topic_dir).resolve()
            if not is_relative_to(resolved, expected):
                errors.append(f"Knowledge notes must be saved under {expected}.")

    text = path.read_text(encoding="utf-8")
    frontmatter, body = split_frontmatter(text)

    if content_type != "knowledge" and not QUESTION_CALLOUT_RE.search(body):
        errors.append("At least one original problem statement must use > [!question].")
    if FORBIDDEN_HEADING_RE.search(body):
        errors.append("Forbidden process/log heading found in note body.")
    if SOURCE_PATH_RE.search(body):
        errors.append("Source file path or local process path found in note body.")
    if not allow_wikilinks and WIKILINK_RE.search(body):
        errors.append("Wikilinks are present, but related links were not explicitly requested.")

    for line in frontmatter.splitlines():
        match = re.match(r"^([A-Za-z0-9_-]+)\s*:", line)
        if match and match.group(1).lower() in BAD_FRONTMATTER_KEYS:
            errors.append(f"Process metadata field in frontmatter: {match.group(1)}.")

    errors.extend(validate_frac_usage(text))
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("markdown", type=Path)
    parser.add_argument("--vault-root", type=Path, default=DEFAULT_VAULT_ROOT)
    parser.add_argument("--allow-wikilinks", action="store_true")
    parser.add_argument(
        "--explicit-destination",
        action="store_true",
        help="Skip default problem/knowledge destination checks because the user specified a destination.",
    )
    parser.add_argument(
        "--content-type",
        choices=("problem", "knowledge", "unspecified"),
        default="unspecified",
        help="Use problem for exercise/answer notes; knowledge for high-school concept notes.",
    )
    parser.add_argument("--topic-dir", help="High-school math big-direction folder for knowledge notes.")
    args = parser.parse_args()

    if not args.markdown.exists():
        print(f"FAIL: file does not exist: {args.markdown}", file=sys.stderr)
        return 2

    errors = validate(
        args.markdown,
        args.vault_root,
        args.allow_wikilinks,
        args.content_type,
        args.topic_dir,
        args.explicit_destination,
    )
    if errors:
        print("FAIL")
        for error in errors:
            print(f"- {error}")
        return 1

    print("PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
